LOCATIONS = {
    'poi': [
        ('places_of_interest', 'Places of Interest'),
        ('pokecenters', 'Pokécenters'),
    ],
    'cities': [
        ('sandgem_jubilife', 'Sandgem/Jubilife'),
        ('oreburgh', 'Oreburgh'),
        ('floaroma', 'Floaroma'),
        ('eterna', 'Eterna'),
        ('hearthome', 'Hearthome'),
        ('solaceon', 'Solaceon'),
        ('veilstone', 'Veilstone'),
        ('pastoria', 'Pastoria'),
        ('celestic', 'Celestic'),
        ('canalave', 'Canalave'),
        ('snowpoint', 'Snowpoint'),
        ('sunyshore', 'Sunyshore'),
        ('fight_resort', 'Fight/Resort'),
        ('survival', 'Survival Area'),
    ],
    'hubs': [
        ('jubilife_tv', 'Jubilife TV'),
        ('store', 'Department Store'),
        ('galactic_eterna', 'Galactic Eterna'),
        ('galactic_hq', 'Galactic HQ'),
        ('old_chateau', 'Old Chateau'),
        ('solaceon_ruins', 'Solaceon Ruins'),
        ('pokemansion', 'Pokémon Mansion'),
    ],
    'routes': [
        ('route_208', 'Route 208'),
        ('eterna_forest', 'Eterna Forest'),
        ('route_213_214_222', 'R213, R214, R222'),
        ('great_marsh', 'Great Marsh'),
    ],
    'other': [
        ('mt_coronet', 'Mt Coronet'),
        ('victory_road', 'Victory Road'),
        ('iron_island', 'Iron Island'),
        ('poketch_gts', 'Pokétch + GTS'),
        ('oreburgh_gate', 'Oreburgh Gate'),
        ('surf_hub', 'Surf Hub'),
    ]
}

ENTRANCES = {
    'places_of_interest': [
        ('oreburgh_gym_interior', 'Oreburgh Gym Interior'),
        ('eterna_gym_interior', 'Eterna Gym Interior'),
        ('hearthome_gym_interior', 'Hearthome Gym Interior'),
        ('veilstone_gym_interior', 'Veilstone Gym Interior'),
        ('pastoria_gym_interior', 'Pastoria Gym Interior'),
        ('canalave_gym_interior', 'Canalave Gym Interior'),
        ('snowpoint_gym_interior', 'Snowpoint Gym Interior'),
        ('sunyshore_gym_interior', 'Sunyshore Gym Interior'),
        ('e4_aaron', 'E4 Aaron'),
        ('e4_bertha', 'E4 Bertha'),
        ('e4_flint', 'E4 Flint'),
        ('e4_lucian', 'E4 Lucian'),
        ('champion', 'Champion'),
        ('dialga_palkia', 'Dialga & Palkia'),
        ('cresselia', 'Cresselia'),
        ('darkrai', 'Darkrai'),
        ('heatran', 'Heatran'),
        ('arceus', 'Arceus'),
        ('azelf', 'Azelf'),
        ('uxie', 'Uxie'),
    ],
    'pokecenters': [
         ('sandgem_pc_w', 'Sandgem PC W'),
         ('sandgem_pc_s', 'Sandgem PC S'),
         ('sandgem_pc_e', 'Sandgem PC E'),
         ('jubilife_pc_w', 'Jubilife PC W'),
         ('jubilife_pc_s', 'Jubilife PC S'),
         ('jubilife_pc_e', 'Jubilife PC E'),
         ('oreburgh_pc_w', 'Oreburgh PC W'),
         ('oreburgh_pc_s', 'Oreburgh PC S'),
         ('oreburgh_pc_e', 'Oreburgh PC E'),
         ('floaroma_pc_w', 'Floaroma PC W'),
         ('floaroma_pc_s', 'Floaroma PC S'),
         ('floaroma_pc_e', 'Floaroma PC E'),
         ('eterna_pc_w', 'Eterna PC W'),
         ('eterna_pc_s', 'Eterna PC S'),
         ('eterna_pc_e', 'Eterna PC E'),
         ('hearthome_pc_w', 'Hearthome PC W'),
         ('hearthome_pc_s', 'Hearthome PC S'),
         ('hearthome_pc_e', 'Hearthome PC E'),
         ('solaceon_pc_w', 'Solaceon PC W'),
         ('solaceon_pc_s', 'Solaceon PC S'),
         ('solaceon_pc_e', 'Solaceon PC E'),
         ('veilstone_pc_w', 'Veilstone PC W'),
         ('veilstone_pc_s', 'Veilstone PC S'),
         ('veilstone_pc_e', 'Veilstone PC E'),
         ('pastoria_pc_w', 'Pastoria PC W'),
         ('pastoria_pc_s', 'Pastoria PC S'),
         ('pastoria_pc_e', 'Pastoria PC E'),
         ('celestic_pc_w', 'Celestic PC W'),
         ('celestic_pc_s', 'Celestic PC S'),
         ('celestic_pc_e', 'Celestic PC E'),
         ('canalave_pc_w', 'Canalave PC W'),
         ('canalave_pc_s', 'Canalave PC S'),
         ('canalave_pc_e', 'Canalave PC E'),
         ('snowpoint_pc_w', 'Snowpoint PC W'),
         ('snowpoint_pc_s', 'Snowpoint PC S'),
         ('snowpoint_pc_e', 'Snowpoint PC E'),
         ('sunyshore_pc_w', 'Sunyshore PC W'),
         ('sunyshore_pc_s', 'Sunyshore PC S'),
         ('sunyshore_pc_e', 'Sunyshore PC E'),
         ('victory_road_pc_w', 'Victory Road PC W'),
         ('victory_road_pc_s', 'Victory Road PC S'),
         ('victory_road_pc_e', 'Victory Road PC E'),
         ('pokemon_league_up', 'Pokemon League Up'),
         ('pokemon_league_down', 'Pokemon League Down'),
         ('pokemon_league_n', 'Pokemon League N'),
         ('pokemon_league_s', 'Pokemon League S'),
         ('fight_area_pc_w', 'Fight Area PC W'),
         ('fight_area_pc_s', 'Fight Area PC S'),
         ('fight_area_pc_e', 'Fight Area PC E'),
         ('survival_area_pc_w', 'Survival Area PC W'),
         ('survival_area_pc_s', 'Survival Area PC S'),
         ('survival_area_pc_e', 'Survival Area PC E'),
         ('resort_area_pc_w', 'Resort Area PC W'),
         ('resort_area_pc_s', 'Resort Area PC S'),
         ('resort_area_pc_e', 'Resort Area PC E'),
    ],
    'sandgem_jubilife': [
        ('sandgem_sw', 'Sandgem SW'),
        ('sandgem_s', 'Sandgem S'),
        ('sandgem_mart', 'Sandgem Mart'),
        ('sandgem_pokecenter', 'Sandgem Pokécenter'),
        ('jubilife_pokecenter', 'Jubilife Pokécenter'),
        ('jubilife_trainer_school', 'Jubilife Trainer School'),
        ('jubilife_mart', 'Jubilife Mart'),
        ('jubilife_s', 'Jubilife S'),
        ('jubilife_sw', 'Jubilife SW'),
        ('jubilife_ne', 'Jubilife NE'),
        ('jubilife_gts', 'Jubilife GTS'),
        ('jubilife_tv', 'Jubilife TV'),
        ('jubilife_poketch_w', 'Jubilife Poketch W'),
        ('jubilife_poketch_e', 'Jubilife Poketch E'),
        ('jubilife_ravaged_path', 'Jubilife Ravaged Path'),
        ('jubilife_oreburgh_gate', 'Jubilife Oreburgh Gate'),
        ('jubilife_west_exit', 'Jubilife West Exit'),
    ],
    'oreburgh': [
        ('oreburgh_gym', 'Gym'),
        ('oreburgh_mart', 'Mart'),
        ('oreburgh_pokecenter', 'Pokécenter'),
        ('oreburgh_fossil_lab', 'Fossil Lab'),
        ('oreburgh_mine', 'Mine'),
        ('oreburgh_apartment_nw', 'Apartment NW'),
        ('oreburgh_apartment_n', 'Apartment N'),
        ('oreburgh_apartment_e', 'Apartment E'),
        ('oreburgh_house_w', 'House W'),
        ('oreburgh_house_c', 'House C'),
        ('oreburgh_house_se', 'House SE'),
        ('oreburgh_west_exit', 'West Exit'),
        ('r206_cycle_path', 'R206 Cycle Path'),
        ('r206_wayward_cave', 'R206 Wayward Cave'),
        ('r206_wayward_cave_hidden', 'R206 Wayward Cave Hidden'),
        ('r207_mt_coronet', 'R207 Mt Coronet'),
    ],
    'floaroma': [
        ('floaroma_pokecenter', 'Pokecenter'),
        ('floaroma_mart', 'Mart'),
        ('floaroma_flower_shop', 'Flower Shop'),
        ('floaroma_nw', 'NW'),
        ('floaroma_se', 'SE'),
        ('floaroma_meadow', 'Meadow'),
        ('floaroma_ravaged_path', 'Ravaged Path'),
        ('r205_ironworks', 'R205 Ironworks'),
        ('r205_windworks', 'R205 Windworks'),
        ('r205_eterna_forest', 'R205 Eterna Forest'),
        ('r205_house', 'R205 House'),
    ],
    'eterna': [
        ('eterna_pokecenter', 'Pokecenter'),
        ('eterna_mart', 'Mart'),
        ('eterna_gym', 'Gym'),
        ('eterna_bike_shop', 'Bike Shop'),
        ("eterna_spelunker's_house", "Spelunker's House"),
        ('eterna_city_forest', 'City Forest'),
        ('eterna_apartment', 'Apartment'),
        ('eterna_house_n', 'House N'),
        ('eterna_house_s', 'House S'),
        ('eterna_house_e', 'House E'),
        ('eterna_mt_coronet', 'Mt Coronet'),
        ('eterna_south_exit', 'South Exit'),
    ],
    'hearthome': [
        ('hearthome_pokecenter', 'Pokecenter'),
        ('hearthome_mart', 'Mart'),
        ('hearthome_gym', 'Gym'),
        ('hearthome_contest', 'Contest'),
        ("hearthome_bebe's_house", "Bebe's house"),
        ('hearthome_church', 'Church'),
        ('hearthome_poffin_house', 'Poffin House'),
        ('hearthome_fanclub', 'Fanclub'),
        ('hearthome_apartment_n', 'Apartment N'),
        ('hearthome_apartment_e', 'Apartment E'),
        ('hearthome_amity_square_west', 'Amity Square West'),
        ('hearthome_amity_square_east', 'Amity Square East'),
        ('hearthome_east_exit', 'East Exit'),
        ('hearthome_south_exit', 'South Exit'),
        ('hearthome_west_exit', 'West Exit'),
    ],
    'solaceon': [
        ('solaceon_pokecenter', 'Pokecenter'),
        ('solaceon_mart', 'Mart'),
        ('solaceon_daycare', 'Daycare'),
        ('solaceon_house_n', 'House N'),
        ('solaceon_house_ne', 'House NE'),
        ('solaceon_house_e', 'House E'),
        ('solaceon_house_c', 'House C'),
        ('solaceon_ruins', 'Ruins'),
        ('r209_lost_tower', 'R209 Lost Tower'),
        ('r209_west_exit', 'R209 West Exit'),
        ('r210_cafe_cabin', 'R210 Cafe Cabin'),
        ('r215_east_exit', 'R215 East Exit'),
    ],
    'veilstone': [
        ('veilstone_pokecenter', 'Pokecenter'),
        ('veilstone_mart', 'Mart'),
        ('veilstone_gym', 'Gym'),
        ('veilstone_casino', 'Casino'),
        ('veilstone_galactic_hq_1', 'Galactic HQ 1'),
        ('veilstone_galactic_hq_2', 'Galactic HQ 2'),
        ('veilstone_galactic_hq_3', 'Galactic HQ 3'),
        ('veilstone_galactic_warehouse', 'Galactic Warehouse'),
        ('veilstone_house_n', 'House N'),
        ('veilstone_house_ne', 'House NE'),
        ('veilstone_prize_exchange', 'Prize Exchange'),
        ('veilstone_house_s', 'House S'),
        ('veilstone_house_sw', 'House SW'),
        ('veilstone_south_exit', 'South Exit'),
        ('veilstone_west_exit', 'West Exit'),
    ],
    'pastoria': [
        ('pastoria_pokecenter', 'Pokecenter'),
        ('pastoria_mart', 'Mart'),
        ('pastoria_gym', 'Gym'),
        ('pastoria_great_marsh', 'Great Marsh'),
        ('pastoria_house_ne', 'House NE'),
        ('pastoria_house_se', 'House SE'),
        ('pastoria_house_sw', 'House SW'),
        ('pastoria_house_n', 'House N'),
        ('pastoria_house_c', 'House C'),
        ('pastoria_east_exit', 'East Exit'),
        ('r212_move_tutor', 'R212 Move Tutor'),
        ('r212_pokemon_mansion', 'R212 Pokemon Mansion'),
        ('r212_north_exit', 'R212 North Exit'),
    ],
    'celestic': [
        ('celestic_pokecenter', 'Pokecenter'),
        ('celestic_ruins', 'Ruins'),
        ('celestic_big_house', 'Big House'),
        ('celestic_house_ne', 'House NE'),
        ('celestic_house_nw', 'House NW'),
        ('celestic_house_sw', 'House SW'),
        ('celestic_mt_coronet', 'Mt Coronet'),
        ("r210_grandma's_house", "R210 Grandma's House"),
    ],
    'canalave': [
        ('canalave_pokecenter', 'Pokecenter'),
        ('canalave_mart', 'Mart'),
        ('canalave_gym', 'Gym'),
        ('canalave_library', 'Library'),
        ('canalave_house_ne', 'House NE'),
        ('canalave_house_e', 'House E'),
        ('canalave_house_se', 'House SE'),
        ('canalave_house_w', 'House W'),
        ('canalave_house_sw', 'House SW'),
        ('canalave_iron_island?', 'Iron Island?'),
        ('canalave_east_exit', 'East Exit'),
    ],
    'snowpoint': [
        ('snowpoint_pokecenter', 'Pokecenter'),
        ('snowpoint_mart', 'Mart'),
        ('snowpoint_gym', 'Gym'),
        ('snowpoint_house_nw', 'House NW'),
        ('snowpoint_house_ne', 'House NE'),
        ('snowpoint_temple', 'Temple'),
        ('acuity_lakefront', 'Acuity Lakefront'),
        ('r217_house_n', 'R217 House N'),
        ('r217_house_w', 'R217 House W'),
        ('r216_house_w', 'R216 House W'),
        ('r216_mt_coronet', 'R216 Mt Coronet'),
    ],
    'sunyshore': [
        ('sunyshore_pokecenter', 'Pokecenter'),
        ('sunyshore_mart', 'Mart'),
        ('sunyshore_gym', 'Gym'),
        ('sunyshore_lighthouse', 'Lighthouse'),
        ('sunyshore_market', 'Market'),
        ('sunyshore_house_w', 'House W'),
        ('sunyshore_house_n', 'House N'),
        ('sunyshore_house_ne', 'House NE'),
        ('sunyshore_house_e', 'House E'),
        ('sunyshore_west_exit', 'West Exit'),
    ],
    'fight_resort': [
        ('fight_area_pokecenter', 'Fight Area Pokecenter'),
        ('fight_area_mart', 'Fight Area Mart'),
        ('fight_area_battle_frontier', 'Fight Area Battle Frontier'),
        ('fight_area_s_house', 'Fight Area S House'),
        ('fight_area_c_house', 'Fight Area C House'),
        ('fight_area_north_exit', 'Fight Area North Exit'),
        ('resort_area_pokecenter', 'Resort Area Pokecenter'),
        ('resort_area_villa', 'Resort Area Villa'),
        ('resort_area_ribbon_syndicate', 'Resort Area Ribbon Syndicate'),
        ('resort_area_house', 'Resort Area House'),
        ('r228_s_house', 'R228 S House'),
        ('r228_n_house', 'R228 N House'),
        ('r228_north_exit', 'R228 North Exit'),
    ],
    'survival': [
        ('survival_area_pokecenter', 'Pokecenter'),
        ('survival_area_mart', 'Mart'),
        ('survival_area_n_house', 'N House'),
        ('survival_area_c_house', 'C House'),
        ('survival_area_s_house', 'S House'),
        ('r225_house', 'R225 House'),
        ('r225_south_exit', 'R225 South Exit'),
        ('r226_house', 'R226 House'),
        ('r226_east_exit', 'R226 East Exit'),
        ('r227_house', 'R227 House'),
        ('r227_stark_mountain', 'R227 Stark Mountain'),
    ],
    'jubilife_tv': [
        ('jubilife_tv_1f_up', 'TV 1F Up'),
        ('jubilife_tv_1f_exit', 'TV 1F Exit'),
        ('jubilife_tv_2f_n', 'TV 2F N'),
        ('jubilife_tv_2f_up', 'TV 2F Up'),
        ('jubilife_tv_2f_down', 'TV 2F Down'),
        ('jubilife_tv_3f_nw', 'TV 3F NW'),
        ('jubilife_tv_3f_n', 'TV 3F N'),
        ('jubilife_tv_3f_up', 'TV 3F Up'),
        ('jubilife_tv_3f_down', 'TV 3F Down'),
        ('jubilife_tv_4f_down', 'TV 4F Down'),
    ],
    'store': [
        ('department_store_b1f_up', 'Store B1F Up'),
        ('department_store_1f_down', 'Store 1F Down'),
        ('department_store_1f_exit', 'Store 1F Exit'),
        ('department_store_1f_up', 'Store 1F Up'),
        ('department_store_2f_down', 'Store 2F Down'),
        ('department_store_2f_up', 'Store 2F Up'),
        ('department_store_3f_down', 'Store 3F Down'),
        ('department_store_3f_up', 'Store 3F Up'),
        ('department_store_4f_down', 'Store 4F Down'),
        ('department_store_4f_up', 'Store 4F Up'),
        ('department_store_5f_down', 'Store 5F Down'),
    ],
    'galactic_eterna': [
        ('galactic_eterna_1f_s', 'GA Eterna 1F S'),
        ('galactic_eterna_1f_nw', 'GA Eterna 1F NW'),
        ('galactic_eterna_1f_stairs_n', 'GA Eterna 1F Stairs N'),
        ('galactic_eterna_1f_stairs_ne', 'GA Eterna 1F Stairs NE'),
        ('galactic_eterna_2f_w', 'GA Eterna 2F W'),
        ('galactic_eterna_2f_n', 'GA Eterna 2F N'),
        ('galactic_eterna_2f_e', 'GA Eterna 2F E'),
        ('galactic_eterna_3f_w', 'GA Eterna 3F W'),
        ('galactic_eterna_3f_n', 'GA Eterna 3F N'),
        ('galactic_eterna_3f_e', 'GA Eterna 3F E'),
    ],
    'galactic_hq': [
        ('galactic_hq_1f_south_entrance_e', 'GA HQ 1F South Entrance E'),
        ('galactic_hq_1f_south_entrance_w', 'GA HQ 1F South Entrance W'),
        ('galactic_hq_1f_south_stairs', 'GA HQ 1F South Stairs'),

        ('galactic_hq_1f_ne_stairs', 'GA HQ 1F NE Stairs'),
        ('galactic_hq_1f_ne_warp_w', 'GA HQ 1F NE Warp W'),
        ('galactic_hq_1f_ne_warp_e', 'GA HQ 1F NE Warp E'),

        ('galactic_hq_2f_nw_warp', 'GA HQ 2F NW Warp'),
        ('galactic_hq_2f_nw_down', 'GA HQ 2F NW Down'),
        ('galactic_hq_2f_nw_up', 'GA HQ 2F NW Up'),

        ('galactic_hq_2f_s_stairs', 'GA HQ 2F S Stairs'),
        ('galactic_hq_2f_s_warp_c', 'GA HQ 2F S Warp C'),
        ('galactic_hq_2f_s_warp_ne', 'GA HQ 2F S Warp NE'),
        ('galactic_hq_2f_s_warp_se', 'GA HQ 2F S Warp SE'),

        ('galactic_hq_3f_warp_1', 'GA HQ 3F Warp 1'),
        ('galactic_hq_3f_warp_2', 'GA HQ 3F Warp 2'),
        ('galactic_hq_3f_warp_3', 'GA HQ 3F Warp 3'),
        ('galactic_hq_3f_stairs', 'GA HQ 3F Stairs'),

        ('galactic_hq_4f_stairs', 'GA HQ 4F Stairs'),
        ('galactic_hq_4f_warp_n', 'GA HQ 4F Warp N'),
        ('galactic_hq_4f_warp_ne', 'GA HQ 4F Warp NE'),
        ('galactic_hq_4f_warp_se', 'GA HQ 4F Warp SE'),

        ('galactic_warehouse_b2f_stairs_c', 'GA Warehouse B2F Stairs C'),
        ('galactic_warehouse_b2f_stairs_w', 'GA Warehouse B2F Stairs W'),
        ('galactic_warehouse_b2f_stairs_e', 'GA Warehouse B2F Stairs E'),
    ],
    'old_chateau': [
        ('old_chateau_n', 'Old Chateau N'),
        ('old_chateau_e', 'Old Chateau E'),
        ('old_chateau_s', 'Old Chateau S'),
        ('old_chateau_w', 'Old Chateau W'),
        ('old_chateau_c', 'Old Chateau C'),

        ('old_chateau_2f_room_1', 'Old Chateau 2F Room 1'),
        ('old_chateau_2f_room_2', 'Old Chateau 2F Room 2'),
        ('old_chateau_2f_room_3', 'Old Chateau 2F Room 3'),
        ('old_chateau_2f_room_4', 'Old Chateau 2F Room 4'),
        ('old_chateau_2f_room_5', 'Old Chateau 2F Room 5'),
        ('old_chateau_2f_exit', 'Old Chateau 2F Exit'),
    ],
    'solaceon_ruins': [
        ('solaceon_ruins_1f_nw', '1F NW'),
        ('solaceon_ruins_1f_ne', '1F NE'),
        ('solaceon_ruins_1f_se', '1F SE'),
        ('solaceon_ruins_1f_exit', '1F Exit'),

        ('solaceon_ruins_b1f_nw', 'B1F NW'),
        ('solaceon_ruins_b1f_ne', 'B1F NE'),
        ('solaceon_ruins_b1f_se', 'B1F SE'),
        ('solaceon_ruins_b1f_sw', 'B1F SW'),

        ('solaceon_ruins_b2f_nw', 'B2F NW'),
        ('solaceon_ruins_b2f_ne', 'B2F NE'),
        ('solaceon_ruins_b2f_se', 'B2F SE'),
        ('solaceon_ruins_b2f_sw', 'B2F SW'),
 
        ('solaceon_ruins_b3f_1_nw', 'B3F 1 NW'),
        ('solaceon_ruins_b3f_1_ne', 'B3F 1 NE'),
        ('solaceon_ruins_b3f_1_se', 'B3F 1 SE'),
        ('solaceon_ruins_b3f_1_sw', 'B3F 1 SW'),

        ('solaceon_ruins_b3f_2_nw', 'B3F 2 NW'),
        ('solaceon_ruins_b3f_2_se', 'B3F 2 SE'),
        ('solaceon_ruins_b3f_2_sw', 'B3F 2 SW'),

        ('solaceon_ruins_b4f_nw', 'B4F NW'),
        ('solaceon_ruins_b4f_ne', 'B4F NE'),
        ('solaceon_ruins_b4f_se', 'B4F SE'),
        ('solaceon_ruins_b4f_sw', 'B4F SW'),
    ],
    'pokemansion': [
        ('poke_mansion_s', 'S'),
        ('poke_mansion_w', 'W'),
        ('poke_mansion_e', 'E'),
        ('poke_mansion_n', 'N'),
        ('poke_mansion_room_1', 'Room 1'),
        ('poke_mansion_room_2', 'Room 2'),
        ('poke_mansion_room_3', 'Room 3'),
        ('poke_mansion_room_4', 'Room 4'),
    ],
    'route_208': [
        ('r208_berry_house', 'R208 Berry House'),
        ('r208_east_exit', 'R208 East Exit'),
        ('r208_west_exit', 'R208 West Exit'),
    ],
    'eterna_forest': [
        ('eterna_forest_old_chateau', 'Old Chateau'),
        ('eterna_forest_east_exit', 'East Exit'),
        ('eterna_forest_south_exit', 'South Exit'),
    ],
    'route_213_214_222': [
        ('r214_maniac_tunnel', 'R214 Maniac Tunnel'),
        ('r214_sendoff_spring', 'R214 Sendoff Spring'),
        ('r214_north_exit', 'R214 North Exit'),
        ('valor_lakefront', 'Valor Lakefront'),
        ('hotel_grand_lake_nw', 'Hotel Grand Lake NW'),
        ('hotel_grand_lake_n', 'Hotel Grand Lake N'),
        ('hotel_grand_lake_ne', 'Hotel Grand Lake NE'),
        ('hotel_grand_lake_w', 'Hotel Grand Lake W'),
        ('hotel_grand_lake_e', 'Hotel Grand Lake E'),
        ('hotel_grand_lake_se', 'Hotel Grand Lake SE'),
        ('hotel_grand_lake_s', 'Hotel Grand Lake S'),
        ('r222_house_w', 'R222 House W'),
        ('r222_house_e', 'R222 House E'),
        ('r222_east_exit', 'R222 East Exit'),
    ],
    'great_marsh': [
        ('great_marsh_s', 'Great Marsh S'),
        ('great_marsh_n', 'Great Marsh N'),
        ('great_marsh_up', 'Great Marsh Up'),
    ],
    'mt_coronet': [
        ('mt_coronet_1f_north_stairs', '1F North Stairs'),
        ('mt_coronet_1f_east_exit', '1F East Exit'),
        ('mt_coronet_1f_south_exit', '1F South Exit'),
        ('mt_coronet_1f_west_exit', '1F West Exit'),

        ('mt_coronet_1f_2_south_stairs', '1F 2 South Stairs'),
        ('mt_coronet_1f_2_regice_cave', '1F 2 Regice Cave'),
        ('mt_coronet_1f_2_west_exit', '1F 2 West Exit'),

        ('mt_coronet_1f_3_ne_stairs', '1F 3 NE Stairs'),
        ('mt_coronet_1f_3_east_exit', '1F 3 East Exit'),
        ('mt_coronet_1f_3_west_exit', '1F 3 West Exit'),

        ('mt_coronet_2f_se_stairs', '2F SE Stairs'),
        ('mt_coronet_2f_n_cave', '2F N Cave'),
        ('mt_coronet_2f_sw_exit', '2F SW Exit'),

        ('mt_coronet_3f_west_stairs', '3F West Stairs'),
        ('mt_coronet_3f_east_stairs', '3F East Stairs'),
        ('mt_coronet_3f_west_exit', '3F West Exit'),

        ('mt_coronet_peak_sw_cave', 'Peak SW Cave'),
        ('mt_coronet_peak_w_cave', 'Peak W Cave'),
        ('mt_coronet_peak_e_cave', 'Peak E Cave'),
        ('mt_coronet_peak_nw_cave', 'Peak NW Cave'),
    ],
    'victory_road': [
        ('victory_road_1f_nw_stairs', '1F NW Stairs'),
        ('victory_road_1f_w_stairs', '1F W Stairs'),
        ('victory_road_1f_sw_stairs', '1F SW Stairs'),
        ('victory_road_1f_ne_stairs', '1F NE Stairs'),
        ('victory_road_1f_e_stairs', '1F E Stairs'),
        ('victory_road_1f_se_stairs', '1F SE Stairs'),
        ('victory_road_1f_north_exit', '1F North Exit'),
        ('victory_road_1f_south_exit', '1F South Exit'),

        ('victory_road_b1f_nw_stairs', 'B1F NW Stairs'),
        ('victory_road_b1f_w_stairs', 'B1F W Stairs'),
        ('victory_road_b1f_sw_stairs', 'B1F SW Stairs'),
    ],
    'iron_island': [
        ('iron_island_exterior_entrance', 'Exterior Entrance'),
        ('iron_island_exterior_house', 'Exterior House'),
        ('iron_island_exterior_exit', 'Exterior Exit'),

        ('iron_island_1f_w', '1F W'),
        ('iron_island_1f_e', '1F E'),
        ('iron_island_1f_exit', '1F Exit'),

        ('iron_island_b1f_nw', 'B1F NW'),
        ('iron_island_b1f_sw', 'B1F SW'),
        ('iron_island_b1f_se', 'B1F SE'),

        ('iron_island_b3f_nw', 'B3F NW'),
        ('iron_island_b3f_registeel', 'B3F Registeel'),
        ('iron_island_b3f_se', 'B3F SE'),
    ],
    'poketch_gts': [
        ('poketch_interior_sw', 'Poketch Interior SW'),
        ('poketch_interior_se', 'Poketch Interior SE'),
        ('poketch_interior_up', 'Poketch Interior Up'),
        ('gts_1f_warp_w', 'GTS 1F Warp W'),
        ('gts_1f_warp_e', 'GTS 1F Warp E'),
        ('gts_1f_exit', 'GTS 1F Exit'),
    ],
    'oreburgh_gate': [
        ('oreburgh_gate_stairs', 'Stairs'),
        ('oreburgh_gate_east_exit', 'East Exit'),
        ('oreburgh_gate_west_exit', 'West Exit'),
    ],
    'surf_hub': [
        ('lake_verity', 'Lake Verity'),
        ('lake_valor', 'Lake Valor'),
        ('lake_acuity', 'Lake Acuity'),
        ('r221_house', 'R221 House'),
        ('r221_pal_park', 'R221 Pal Park'),
        ('r205_floaroma_meadow', 'R205 Floaroma Meadow'),
    ],
}
